export const allCards: Card[] = [
	{
		id: 0,
		title: '별',
		info: 'info',
		description: 'desc',
		fileName: 'star',
		items: [0, 1, 2],
	},
	{
		id: 1,
		title: '마법사',
		info: 'info',
		description: 'desc',
		fileName: 'magician',
		items: [3, 4, 5],
	},
	{
		id: 2,
		title: '황제',
		info: 'info',
		description: 'desc',
		fileName: 'emperor',
		items: [6, 7, 8],
	},
	{
		id: 3,
		title: '정의',
		info: 'info',
		description: 'desc',
		fileName: 'justice',
		items: [9, 10, 11],
	},
	{
		id: 4,
		title: '은둔자',
		info: 'info',
		description: 'desc',
		fileName: 'hermit',
		items: [12, 13, 14],
	},
	{
		id: 5,
		title: '절제',
		info: 'info',
		description: 'desc',
		fileName: 'temperance',
		items: [15, 16, 17],
	},
]
