export const allCards: Card[] = [
	{
		id: 0,
		title: '별',
		info: 'info',
		description: '별 카드는 낙천적이고 순수한 정신을 추구합니다. <br /> 하지만 막연하게 낙관적인 꿈만 꾸다가 수습 불가능한 상황을 마주할 가능성이 있습니다.',
		fileName: 'star',
		items: [0, 1, 2],
	},
	{
		id: 1,
		title: '마법사',
		info: 'info',
		description: '마법사 카드는 무궁무진한 가능성과 잠재력을 의미합니다. <br /> 이제 막 새로운 것을 시작하려는 당신은 아무도 몰랐던 잠재력이 있을 가능성이 있습니다.',
		fileName: 'magician',
		items: [3, 4, 5],
	},
	{
		id: 2,
		title: '황제',
		info: 'info',
		description: '황제 카드는 권위적이고 열정적인 정신을 추구합니다. <br /> 매사에 부족함이 없는 당신은 원하는 것을 가질 가능성이 있습니다.',
		fileName: 'emperor',
		items: [6, 7, 8],
	},
	{
		id: 3,
		title: '정의',
		info: 'info',
		description: '정의 카드는 어느 한 쪽으로도 치우치지 않는 저울의 정신을 추구합니다. <br /> 어쩌면 가까운 관계에 있는 사람이 당신을 가늠하고 있을 가능성이 있습니다.',
		fileName: 'justice',
		items: [9, 10, 11],
	},
	{
		id: 4,
		title: '은둔자',
		info: 'info',
		description: '은둔자 카드는 속세와 떨어져 정신적인 것을 추구합니다. <br /> 홀로 여정을 떠나는 모습은 고독해 보이나, 세상과 떨어져 내가 하고자 하는 것에 도달할 수 있습니다.',
		fileName: 'hermit',
		items: [12, 13, 14],
	},
	{
		id: 5,
		title: '절제',
		info: 'info',
		description: '절제 카드는 차분한 중용과 잔잔한 중재를 추구합니다. <br /> 내 주변에 불안했던 것이 완만해지고 안정이 찾아올 가능성이 있습니다.',
		fileName: 'temperance',
		items: [15, 16, 17],
	},
]
