export const allCards: Card[] = [
	{
		id: 0,
		title: '과거',
		info: '은둔자',
		image: 'cards/star.png',
		smallImage: 'cards/small/star.png',
		items: [0, 1, 2],
	},
	{
		id: 1,
		title: '과거',
		info: '은둔자',
		image: 'cards/magician.png',
		smallImage: 'cards/small/magician.png',
		items: [3, 4, 5],
	},
	{
		id: 2,
		title: '과거',
		info: '은둔자',
		image: 'cards/emperor.png',
		smallImage: 'cards/small/emperor.png',
		items: [6, 7, 8],
	},
	{
		id: 3,
		title: '과거',
		info: '은둔자',
		image: 'cards/justice.png',
		smallImage: 'cards/small/justice.png',
		items: [9, 10, 11],
	},
	{
		id: 4,
		title: '과거',
		info: '은둔자',
		image: 'cards/hermit.png',
		smallImage: 'cards/small/hermit.png',
		items: [12, 13, 14],
	},
	{
		id: 5,
		title: '과거',
		info: '은둔자',
		image: 'cards/temperance.png',
		smallImage: 'cards/small/temperance.png',
		items: [15, 16, 17],
	},
]
